
//----------------------------------------------------
// The following code was generated by CUP v0.11b 20160615 (GIT 4ac7450)
//----------------------------------------------------

/** CUP generated class containing symbol constants. */
public class sym {
  /* terminals */
  public static final int DIVEQ = 38;
  public static final int MASMAS = 33;
  public static final int DISTINTO = 14;
  public static final int MENOSMENOS = 34;
  public static final int AC = 44;
  public static final int POR = 29;
  public static final int MODEQ = 39;
  public static final int COMMENT = 11;
  public static final int CAST_FLOAT = 8;
  public static final int CASE = 53;
  public static final int INTERR = 54;
  public static final int INT = 5;
  public static final int FOR = 55;
  public static final int CP = 41;
  public static final int NOT = 48;
  public static final int AND = 47;
  public static final int ELSEIF = 51;
  public static final int IGUAL = 13;
  public static final int OR = 46;
  public static final int IN = 23;
  public static final int DIV = 30;
  public static final int NUM = 3;
  public static final int CC = 45;
  public static final int IF = 52;
  public static final int CAST_INT = 7;
  public static final int EOF = 0;
  public static final int ASIG = 12;
  public static final int AMP = 25;
  public static final int error = 1;
  public static final int COMA = 10;
  public static final int FLOATNUM = 4;
  public static final int MODULO = 31;
  public static final int MENOS = 28;
  public static final int MENOR = 16;
  public static final int BREAK = 20;
  public static final int IDENT = 2;
  public static final int MASEQ = 35;
  public static final int PUNTERO = 26;
  public static final int CLL = 43;
  public static final int MENOSUNARIO = 32;
  public static final int SWITCH = 58;
  public static final int ELVIS = 60;
  public static final int MAYOR = 15;
  public static final int POREQ = 37;
  public static final int ELSE = 22;
  public static final int MAYORIG = 17;
  public static final int TO = 57;
  public static final int WHILE = 50;
  public static final int DEFAULT = 19;
  public static final int FLOAT = 6;
  public static final int MENORIG = 18;
  public static final int ALL = 42;
  public static final int DOWNTO = 56;
  public static final int MENOSEQ = 36;
  public static final int AP = 40;
  public static final int DP = 59;
  public static final int DO = 49;
  public static final int PRINT = 24;
  public static final int STEP = 21;
  public static final int PYC = 9;
  public static final int MAS = 27;
  public static final String[] terminalNames = new String[] {
  "EOF",
  "error",
  "IDENT",
  "NUM",
  "FLOATNUM",
  "INT",
  "FLOAT",
  "CAST_INT",
  "CAST_FLOAT",
  "PYC",
  "COMA",
  "COMMENT",
  "ASIG",
  "IGUAL",
  "DISTINTO",
  "MAYOR",
  "MENOR",
  "MAYORIG",
  "MENORIG",
  "DEFAULT",
  "BREAK",
  "STEP",
  "ELSE",
  "IN",
  "PRINT",
  "AMP",
  "PUNTERO",
  "MAS",
  "MENOS",
  "POR",
  "DIV",
  "MODULO",
  "MENOSUNARIO",
  "MASMAS",
  "MENOSMENOS",
  "MASEQ",
  "MENOSEQ",
  "POREQ",
  "DIVEQ",
  "MODEQ",
  "AP",
  "CP",
  "ALL",
  "CLL",
  "AC",
  "CC",
  "OR",
  "AND",
  "NOT",
  "DO",
  "WHILE",
  "ELSEIF",
  "IF",
  "CASE",
  "INTERR",
  "FOR",
  "DOWNTO",
  "TO",
  "SWITCH",
  "DP",
  "ELVIS"
  };
}

