
//----------------------------------------------------
// The following code was generated by CUP v0.11b 20160615 (GIT 4ac7450)
//----------------------------------------------------

/** CUP generated class containing symbol constants. */
public class sym {
  /* terminals */
  public static final int DISTINTO = 15;
  public static final int POR = 28;
  public static final int CHAR = 7;
  public static final int CASE = 22;
  public static final int INTERR = 9;
  public static final int INT = 6;
  public static final int FOR = 42;
  public static final int CP = 33;
  public static final int NOT = 38;
  public static final int AND = 37;
  public static final int IGUAL = 14;
  public static final int OR = 36;
  public static final int DIV = 29;
  public static final int NUM = 3;
  public static final int TYPEDEF = 8;
  public static final int IF = 20;
  public static final int EOF = 0;
  public static final int ASIG = 13;
  public static final int TRUE = 4;
  public static final int error = 1;
  public static final int COMA = 12;
  public static final int MODULO = 30;
  public static final int MENOS = 27;
  public static final int MENOR = 17;
  public static final int BREAK = 24;
  public static final int IDENT = 2;
  public static final int CLL = 35;
  public static final int MENOSUNARIO = 31;
  public static final int SWITCH = 21;
  public static final int MAYOR = 16;
  public static final int ELSE = 41;
  public static final int MAYORIG = 18;
  public static final int WHILE = 40;
  public static final int DEFAULT = 23;
  public static final int MENORIG = 19;
  public static final int ALL = 34;
  public static final int FALSE = 5;
  public static final int AP = 32;
  public static final int DP = 10;
  public static final int DO = 39;
  public static final int PRINT = 25;
  public static final int PYC = 11;
  public static final int MAS = 26;
  public static final String[] terminalNames = new String[] {
  "EOF",
  "error",
  "IDENT",
  "NUM",
  "TRUE",
  "FALSE",
  "INT",
  "CHAR",
  "TYPEDEF",
  "INTERR",
  "DP",
  "PYC",
  "COMA",
  "ASIG",
  "IGUAL",
  "DISTINTO",
  "MAYOR",
  "MENOR",
  "MAYORIG",
  "MENORIG",
  "IF",
  "SWITCH",
  "CASE",
  "DEFAULT",
  "BREAK",
  "PRINT",
  "MAS",
  "MENOS",
  "POR",
  "DIV",
  "MODULO",
  "MENOSUNARIO",
  "AP",
  "CP",
  "ALL",
  "CLL",
  "OR",
  "AND",
  "NOT",
  "DO",
  "WHILE",
  "ELSE",
  "FOR"
  };
}

