
//----------------------------------------------------
// The following code was generated by CUP v0.11b 20160615 (GIT 4ac7450)
//----------------------------------------------------

/** CUP generated class containing symbol constants. */
public class sym {
  /* terminals */
  public static final int DIVEQ = 38;
  public static final int MASMAS = 31;
  public static final int DISTINTO = 12;
  public static final int MENOSMENOS = 32;
  public static final int POWER = 29;
  public static final int POR = 26;
  public static final int CHAR = 5;
  public static final int MASMASR = 33;
  public static final int CASE = 20;
  public static final int INTERR = 51;
  public static final int INT = 4;
  public static final int FOR = 53;
  public static final int CP = 40;
  public static final int NOT = 45;
  public static final int AND = 44;
  public static final int ELSEIF = 49;
  public static final int IGUAL = 11;
  public static final int OR = 43;
  public static final int MENOSMENOSR = 34;
  public static final int DIV = 27;
  public static final int NUM = 3;
  public static final int TYPEDEF = 7;
  public static final int IF = 50;
  public static final int EOF = 0;
  public static final int ASIG = 10;
  public static final int TRUE = 17;
  public static final int error = 1;
  public static final int COMA = 9;
  public static final int MODULO = 28;
  public static final int MENOS = 25;
  public static final int MENOR = 14;
  public static final int BREAK = 22;
  public static final int IDENT = 2;
  public static final int MASEQ = 35;
  public static final int CLL = 42;
  public static final int MENOSUNARIO = 30;
  public static final int SWITCH = 19;
  public static final int MAYOR = 13;
  public static final int POREQ = 37;
  public static final int ELSE = 48;
  public static final int MAYORIG = 15;
  public static final int WHILE = 47;
  public static final int DEFAULT = 21;
  public static final int FLOAT = 6;
  public static final int MENORIG = 16;
  public static final int ALL = 41;
  public static final int MENOSEQ = 36;
  public static final int FALSE = 18;
  public static final int AP = 39;
  public static final int DP = 52;
  public static final int DO = 46;
  public static final int PRINT = 23;
  public static final int PYC = 8;
  public static final int MAS = 24;
  public static final String[] terminalNames = new String[] {
  "EOF",
  "error",
  "IDENT",
  "NUM",
  "INT",
  "CHAR",
  "FLOAT",
  "TYPEDEF",
  "PYC",
  "COMA",
  "ASIG",
  "IGUAL",
  "DISTINTO",
  "MAYOR",
  "MENOR",
  "MAYORIG",
  "MENORIG",
  "TRUE",
  "FALSE",
  "SWITCH",
  "CASE",
  "DEFAULT",
  "BREAK",
  "PRINT",
  "MAS",
  "MENOS",
  "POR",
  "DIV",
  "MODULO",
  "POWER",
  "MENOSUNARIO",
  "MASMAS",
  "MENOSMENOS",
  "MASMASR",
  "MENOSMENOSR",
  "MASEQ",
  "MENOSEQ",
  "POREQ",
  "DIVEQ",
  "AP",
  "CP",
  "ALL",
  "CLL",
  "OR",
  "AND",
  "NOT",
  "DO",
  "WHILE",
  "ELSE",
  "ELSEIF",
  "IF",
  "INTERR",
  "DP",
  "FOR"
  };
}

